plugins:
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true

service: my-app
provider:
  name: aws
  runtime: nodejs18.x

functions:
  ping:
    handler: dist/lambda.api
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
