version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor:
      name: node/default
      tag: 18.16.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  my-workflow:
    jobs:
      - build_and_test
